### ISSUE TITLE
HAB Ballon is tracking?

### ISSUE THREAD

**Issue by xpix** [raspberrypi/skygate#10]
Hmm, i don't found a balloon tracking on habhub tracker.habhub.org ... just the gps position of chaising car, but where is my balloon data on this tracker?

**Comment by daveake** [comment]
Have you created a payload document for your balloon?  If so, does it work?

See https://ukhas.org.uk/guides:documents regarding how to create and test payload documents.

**Comment by xpix** [comment]
Yes sorry, after creating this document i can see my balloon. Works as designed :)

**Comment by daveake** [comment]
Excellent :)

The habhub system seems to be slow today - I saw several minutes delay
during a flight earlier.
