### ISSUE TITLE
How can i call the test files

### ISSUE THREAD

**Issue by xpix** [raspberrypi/skygate#5]
Hello,

i'll test the lora connection between this boards:

Tracker: dragino Lora/GPS Hat (http://wiki.dragino.com/index.php?title=Lora/GPS_HAT)
Skygate: pi-gate (https://github.com/pi-gate/driver) 

Problem i can't start the test_lora.py, maybe i'm wrong:

```
i@XSkyGateway:/usr/lib/python3/dist-packages/skygate $ python3 ./test_lora.py
Traceback (most recent call last):
  File "./test_lora.py", line 1, in <module>
    from skygate.lora import *
  File "/usr/lib/python3/dist-packages/skygate/skygate.py", line 7, in <module>
    import skygate.misc
ImportError: No module named 'skygate.misc'; 'skygate' is not a package
```

How can i call this files on my raspbian with installed skygate or from sources.

cu
Frank

**Comment by XECDesign** [comment]
Does it work if you replace `skygate.misc` with just misc in that .py file? If there are any other `skygate.something` imports, remove the `skygate.` part from those too

**Comment by xpix** [comment]
yes thx
